services:

  # ===============================================================================================
  # Client worker
  # ===============================================================================================
  worker:
    build: "./"
    env_file:
      - "./.env"